# Generated by Django 6.0.8 on 2026-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unlock',
            name='gateway_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
