# Generated by Django 6.0.8 on 2026-08-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0002_unlock_order_id_alter_unlock_gateway_txn_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accurate', models.BooleanField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='unlocks.unlock')),
            ],
            options={
                'unique_together': {('unlock',)},
            },
        ),
    ]
