# Generated by Django 4.2.30 on 2026-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
