# Generated by Django 4.2.30 on 2026-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0004_unlock_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'Direct UPI')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='unlock',
            name='utr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
