# Generated by Django 4.2.30 on 2026-08-11 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlocks', '0006_unlock_guest_phone_alter_unlock_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlock',
            name='guest_phone',
        ),
        migrations.AlterField(
            model_name='unlock',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
