# Generated by Django 4.2.30 on 2026-08-13 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlocks', '0007_remove_unlock_guest_phone_alter_unlock_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('single_14', 'Single Unlock (₹14)'), ('starter_39', 'Starter Pass (₹39)'), ('smart_79', 'Smart Pass (₹79)'), ('pro_129', 'Pro Hunter Pass (₹129)')], max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_remaining', models.IntegerField(default=0)),
                ('agreement_credits_remaining', models.IntegerField(default=0)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('depleted', 'Depleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('extension_used', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
