# Generated by Django 4.2.30 on 2026-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0009_unlock_created_at_idempotencykey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('depleted', 'Depleted'), ('failed', 'Failed')], default='active', max_length=20),
        ),
    ]
