# Generated by Django 4.2.30 on 2026-08-16 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlocks', '0010_alter_buyersubscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerListingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default='3pack', max_length=50)),
                ('category', models.CharField(default='all', max_length=50)),
                ('credits_total', models.IntegerField(default=1)),
                ('credits_remaining', models.IntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_listing_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
