# Generated by Django 4.2.30 on 2026-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0011_ownerlistingpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlock',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('rented', 'Deal Closed / Rented'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
