# Generated by Django 4.2.30 on 2026-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0013_add_processed_webhook_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlock',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
