# Generated by Django 4.2.30 on 2026-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0014_add_refunded_to_unlock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersubscription',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'Direct UPI'), ('bypass', 'Bypassed')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='buyersubscription',
            name='utr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
