# Generated by Django 4.2.30 on 2026-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0015_buyersubscription_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerlistingpass',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'Direct UPI'), ('bypass', 'Bypassed')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='ownerlistingpass',
            name='utr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
