# Generated by Django 4.2.30 on 2026-08-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0016_ownerlistingpass_payment_method_ownerlistingpass_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlock',
            name='buyer_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_items', to='unlocks.buyersubscription'),
        ),
    ]
