# Generated by Django 4.2.30 on 2026-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocks', '0017_unlock_buyer_subscription'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='buyersubscription',
            index=models.Index(fields=['buyer', 'status'], name='unlocks_buy_buyer_i_d49fed_idx'),
        ),
        migrations.AddIndex(
            model_name='buyersubscription',
            index=models.Index(fields=['gateway_txn_id'], name='unlocks_buy_gateway_ceb0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='buyersubscription',
            index=models.Index(fields=['order_id'], name='unlocks_buy_order_i_f3879c_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerlistingpass',
            index=models.Index(fields=['owner', 'status'], name='unlocks_own_owner_i_d85fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerlistingpass',
            index=models.Index(fields=['gateway_txn_id'], name='unlocks_own_gateway_cbd4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerlistingpass',
            index=models.Index(fields=['order_id'], name='unlocks_own_order_i_50baba_idx'),
        ),
        migrations.AddIndex(
            model_name='unlock',
            index=models.Index(fields=['buyer', 'property', 'status'], name='unlocks_unl_buyer_i_c6de78_idx'),
        ),
        migrations.AddIndex(
            model_name='unlock',
            index=models.Index(fields=['status', 'created_at'], name='unlocks_unl_status_989fe9_idx'),
        ),
    ]
