# Generated by Django 4.2.30 on 2026-09-04 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlocks', '0018_buyersubscription_unlocks_buy_buyer_i_d49fed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'No Dispute (Accurate)'), ('pending', 'Pending Admin Review'), ('approved', 'Approved & Refunded'), ('rejected', 'Rejected / Fake Claim')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.CharField(blank=True, choices=[('already_rented', 'Already Rented Out'), ('wrong_number', 'Wrong / Inactive Phone Number'), ('broker_demanding_commission', 'Broker Demanding Commission'), ('fake_photos_or_price', 'Fake Photos or Price Mismatch'), ('other', 'Other Issue')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
    ]
