# Generated by Django 6.0.8 on 2026-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fraud_flag_count',
            field=models.IntegerField(default=0),
        ),
    ]
