# Generated by Django 6.0.8 on 2026-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fraud_flag_count'),
        ('properties', '0004_city_locality_property_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_cities',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='properties.city'),
        ),
    ]
