# Generated by Django 4.2.30 on 2026-08-07 05:09

from django.db import migrations


def backfill_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.role:
            user.roles = [user.role]
            user.save(update_fields=['roles'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_force_password_change_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_roles, reverse_code=migrations.RunPython.noop),
    ]
