# Generated by Django 4.2.30 on 2026-08-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettingsVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('admin_phone', models.CharField(max_length=20)),
                ('security_question', models.CharField(max_length=255)),
                ('security_answer_hash', models.CharField(max_length=255)),
                ('is_configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_vault', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
