# Generated by Django 4.2.30 on 2026-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminsettingsvault'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_admin_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
