# Generated by Django 4.2.30 on 2026-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_sub_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
