# Generated by Django 4.2.30 on 2026-08-15 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_has_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('aadhaar_front_url', models.TextField(blank=True, null=True)),
                ('aadhaar_back_url', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_card_url', models.TextField(blank=True, null=True)),
                ('karnataka_rera_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license_no', models.CharField(blank=True, max_length=50, null=True)),
                ('selfie_url', models.TextField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('submitted', 'Submitted - Under Review'), ('verified', 'Verified Partner'), ('rejected', 'Verification Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
