# Generated by Django 4.2.30 on 2026-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_agentkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dpdp_consent_given',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dpdp_consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dpdp_consent_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
