# Generated by Django 4.2.30 on 2026-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_dpdp_consent_given_user_dpdp_consent_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dpdp_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
