# Generated by Django 4.2.30 on 2026-08-18 07:43

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_dpdp_consent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentkyc',
            name='aadhaar_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentkyc',
            name='bank_account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentkyc',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentkyc',
            name='pan_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentkyc',
            name='upi_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
