# Generated by Django 4.2.30 on 2026-08-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ownership_document_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
