# Generated by Django 4.2.30 on 2026-09-04 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_owner_kyc_status_user_ownership_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='Support Assistance', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='127.0.0.1', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['admin', '-started_at'], name='accounts_im_admin_i_282612_idx'), models.Index(fields=['target_user', '-started_at'], name='accounts_im_target__5b8c29_idx'), models.Index(fields=['is_active'], name='accounts_im_is_acti_e44c64_idx')],
            },
        ),
    ]
