# Generated by Django 4.2.30 on 2026-08-11 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0002_alter_visitbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitbooking',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='visitbooking',
            name='guest_phone',
        ),
        migrations.AlterField(
            model_name='visitbooking',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
