# Generated by Django 6.0.8 on 2026-08-05 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('exact_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('exact_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('sold', 'Sold'), ('rented', 'Rented'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('consent_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='properties__status_6427a0_idx'), models.Index(fields=['agent'], name='properties__agent_i_e9760d_idx'), models.Index(fields=['created_at'], name='properties__created_72ecc3_idx')],
            },
        ),
    ]
