# Generated by Django 6.0.8 on 2026-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_consentotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
