# Generated by Django 6.0.8 on 2026-08-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_city_locality_property_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='voice_note_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
