# Generated by Django 6.0.8 on 2026-08-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_otpverification_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
