# Generated by Django 4.2.30 on 2026-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_duplicate_of_property_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='onboarding_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='onboarding_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('qr', 'QR Code'), ('razorpay', 'Razorpay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='onboarding_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='unlock_fee',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
    ]
