# Generated by Django 4.2.30 on 2026-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_onboarding_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.IntegerField(blank=True, help_text='Carpet area in Sq.Ft.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi-Furnished'), ('fully', 'Fully-Furnished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_policy',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed')], default='not_allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_tenants',
            field=models.CharField(choices=[('any', 'Any'), ('family', 'Family Only'), ('bachelors', 'Bachelors Allowed'), ('company', 'Company Lease')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
