# Generated by Django 4.2.30 on 2026-08-07 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0009_property_amenities_property_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='added_by',
            field=models.CharField(default='self', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_document',
            field=models.FileField(blank=True, null=True, upload_to='ownership_docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('pending_docs', 'Pending Documents'), ('pending_review', 'Pending Review'), ('verified', 'Verified')], default='pending_docs', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
