# Generated by Django 4.2.30 on 2026-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_added_by_property_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_upi_id', models.CharField(default='rentlo@ybl', max_length=255)),
                ('buyer_unlock_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('owner_onboarding_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bypass_buyer_payment', models.BooleanField(default=False)),
                ('bypass_owner_payment', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
