# Generated by Django 4.2.30 on 2026-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
