# Generated by Django 4.2.30 on 2026-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_virtual_tour_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal')], default='warm_luxury', max_length=50),
        ),
    ]
