# Generated by Django 4.2.30 on 2026-08-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_platformsettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any Food'), ('veg_only', 'Veg Only'), ('non_veg_allowed', 'Non-Veg Allowed')], default='any', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='preferred_tenants',
            field=models.CharField(choices=[('any', 'Any'), ('family', 'Family Only'), ('bachelors', 'Bachelors Allowed'), ('only_boys', 'Boys Only'), ('only_girls', 'Girls Only'), ('company', 'Company Lease')], default='any', max_length=20),
        ),
    ]
