# Generated by Django 4.2.30 on 2026-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_food_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_utr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('under_negotiation', 'Under Negotiation'), ('sold', 'Sold'), ('rented', 'Rented'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
