# Generated by Django 4.2.30 on 2026-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_city_registration_fee_property_registration_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='registration_payment_gateway',
            field=models.CharField(choices=[('upi', 'Direct UPI'), ('razorpay', 'Razorpay')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='registration_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('razorpay', 'Razorpay')], max_length=20, null=True),
        ),
    ]
