# Generated by Django 4.2.30 on 2026-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_platformsettings_registration_payment_gateway_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformsettings',
            old_name='registration_payment_gateway',
            new_name='admin_payment_gateway',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='agent_payment_gateway',
            field=models.CharField(choices=[('upi', 'Direct UPI'), ('razorpay', 'Razorpay')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_payment_gateway',
            field=models.CharField(choices=[('upi', 'Direct UPI'), ('razorpay', 'Razorpay')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_payment_gateway',
            field=models.CharField(choices=[('upi', 'Direct UPI'), ('razorpay', 'Razorpay')], default='upi', max_length=20),
        ),
    ]
