# Generated by Django 4.2.30 on 2026-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_rename_registration_payment_gateway_platformsettings_admin_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='exact_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
