# Generated by Django 6.0.8 on 2026-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_exact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land / Plot')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('pg', 'PG / Co-living'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('residential_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('pg', 'PG / Co-living'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('residential_plot', 'Residential Plot'), ('commercial_plot', 'Commercial Plot'), ('agricultural_land', 'Agricultural Land'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
    ]
