# Generated by Django 4.2.30 on 2026-08-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_property_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commercial_building_type',
            field=models.CharField(blank=True, choices=[('independent', 'Independent Building'), ('business_park', 'Business Park'), ('complex', 'Commercial Complex')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_central_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_pantry',
            field=models.CharField(blank=True, choices=[('wet', 'Wet Pantry'), ('dry', 'Dry Pantry'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='commercial_washrooms',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='covered_parking_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='gated_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='heavy_vehicle_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='industrial_power_capacity_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_term_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lock_in_period_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_included_in_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='open_parking_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_attached_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_food_provided',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_sharing_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('four_plus', 'Four+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.CharField(blank=True, choices=[('full', 'Full'), ('partial', 'Partial'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='retail_frontage_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='super_built_up_area',
            field=models.IntegerField(blank=True, help_text='Super built-up area in Sq.Ft.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='warehouse_ceiling_height_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='warehouse_floor_load_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply',
            field=models.CharField(blank=True, choices=[('24x7', '24/7 Water'), ('corporation', 'Corporation'), ('borewell', 'Borewell')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('pg', 'PG / Co-living'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('pg', 'PG / Co-living'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
    ]
