# Generated by Django 4.2.30 on 2026-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_commercial_building_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='require_otp_for_saves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_otp_for_unlocks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_otp_for_visits',
            field=models.BooleanField(default=True),
        ),
    ]
