# Generated by Django 4.2.30 on 2026-08-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_platformsettings_require_otp_for_saves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='require_otp_for_saves',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='require_otp_for_unlocks',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='require_otp_for_visits',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='require_otp_for_login',
            field=models.BooleanField(default=False),
        ),
    ]
