# Generated by Django 4.2.30 on 2026-08-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_platformsettings_require_otp_for_saves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='require_otp_for_login',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='admin_require_otp_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='admin_require_otp_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='agent_require_otp_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='agent_require_otp_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_require_otp_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_require_otp_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_require_otp_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_require_otp_signup',
            field=models.BooleanField(default=True),
        ),
    ]
