# Generated by Django 4.2.30 on 2026-08-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_remove_platformsettings_require_otp_for_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
