# Generated by Django 4.2.30 on 2026-08-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_platformsettings_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_pass_pro_price',
            field=models.DecimalField(decimal_places=2, default=129.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_pass_smart_price',
            field=models.DecimalField(decimal_places=2, default=79.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_pass_starter_price',
            field=models.DecimalField(decimal_places=2, default=39.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_apt_pg_10pack_price',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_apt_pg_3pack_price',
            field=models.DecimalField(decimal_places=2, default=349.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_apt_pg_6pack_price',
            field=models.DecimalField(decimal_places=2, default=649.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_apt_pg_fee',
            field=models.DecimalField(decimal_places=2, default=149.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_combo_discount_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_commercial_10pack_price',
            field=models.DecimalField(decimal_places=2, default=1199.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_commercial_3pack_price',
            field=models.DecimalField(decimal_places=2, default=449.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_commercial_6pack_price',
            field=models.DecimalField(decimal_places=2, default=799.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_commercial_fee',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_residential_10pack_price',
            field=models.DecimalField(decimal_places=2, default=859.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_residential_3pack_price',
            field=models.DecimalField(decimal_places=2, default=259.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_residential_6pack_price',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='owner_residential_fee',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='under_negotiation_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='unlock_price',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='buyer_unlock_fee',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=10),
        ),
    ]
