# Generated by Django 4.2.30 on 2026-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_platformsettings_buyer_pass_pro_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
