# Generated by Django 4.2.30 on 2026-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_property_has_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='e_stamp_price',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='e_stamp_provider',
            field=models.CharField(choices=[('digio', 'Digio API'), ('signzy', 'Signzy API'), ('leegality', 'Leegality API')], default='digio', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enable_e_stamp_agreements',
            field=models.BooleanField(default=False),
        ),
    ]
