# Generated by Django 4.2.30 on 2026-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_platformsettings_e_stamp_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='e_stamp_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='e_stamp_api_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
