# Generated by Django 4.2.30 on 2026-08-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_platformsettings_e_stamp_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='buyer_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal')], default='warm_luxury', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='dashboard_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal')], default='emerald_minimal', max_length=50),
        ),
    ]
