# Generated by Django 4.2.30 on 2026-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_platformsettingsauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_floor',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('1st', '1st Floor'), ('2nd', '2nd Floor'), ('3rd_plus', '3rd Floor & Above'), ('entire_house', 'Entire House / All Floors')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_hero_spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='pg_gender',
            field=models.CharField(blank=True, choices=[('boys', 'Boys / Male Only'), ('girls', 'Girls / Female Only'), ('coliving', 'Co-Living / Unisex')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
