# Generated by Django 4.2.30 on 2026-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_property_available_beds_property_house_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='otp_bypass_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
