# Generated by Django 4.2.30 on 2026-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_platformsettings_otp_bypass_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('residential', 'Residential'), ('pg', 'PG / Co-Living'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('1bhk', '1 BHK Apartment / House'), ('2bhk', '2 BHK Apartment / House'), ('3bhk', '3 BHK Apartment / House'), ('4bhk', '4 BHK Apartment / House'), ('5bhk', '5+ BHK / Luxury Villa'), ('pg', 'PG / Co-living'), ('pg_hostel', 'Full Co-Living Hostel / PG Building'), ('pg_single', 'Single Occupancy PG Room'), ('pg_double', 'Double Sharing PG Room'), ('pg_triple', 'Triple+ Sharing PG Room'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment / Flat'), ('house', 'Independent House / Villa'), ('builder_floor', 'Builder Floor'), ('studio', '1 RK / Studio Apartment'), ('1bhk', '1 BHK Apartment / House'), ('2bhk', '2 BHK Apartment / House'), ('3bhk', '3 BHK Apartment / House'), ('4bhk', '4 BHK Apartment / House'), ('5bhk', '5+ BHK / Luxury Villa'), ('pg', 'PG / Co-living'), ('pg_hostel', 'Full Co-Living Hostel / PG Building'), ('pg_single', 'Single Occupancy PG Room'), ('pg_double', 'Double Sharing PG Room'), ('pg_triple', 'Triple+ Sharing PG Room'), ('office', 'Office Space'), ('retail', 'Retail Shop / Showroom'), ('warehouse', 'Warehouse / Godown'), ('coworking', 'Co-working Space'), ('industrial', 'Industrial Shed / Building'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20, null=True),
        ),
    ]
