# Generated by Django 4.2.30 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_property_property_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='owner_listing_verification_method',
            field=models.CharField(choices=[('otp', 'OTP Verification'), ('selfie', 'Live Selfie Capture')], default='otp', help_text='Verification method required when staff registers a property on behalf of an owner.', max_length=10),
        ),
    ]
