# Generated by Django 4.2.30 on 2026-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_add_owner_listing_verification_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='buyer_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art')], default='warm_luxury', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='dashboard_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art')], default='emerald_minimal', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art')], default='warm_luxury', max_length=50),
        ),
    ]
