# Generated by Django 4.2.30 on 2026-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_platformsettings_buyer_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='buyer_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage')], default='warm_luxury', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='dashboard_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage')], default='emerald_minimal', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage')], default='warm_luxury', max_length=50),
        ),
    ]
