# Generated by Django 4.2.30 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_platformsettings_buyer_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='buyer_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage'), ('bento_cyber', 'Cyber Obsidian Bento'), ('bento_slate', 'Soft Slate Bento'), ('bento_amber', 'Royal Amber Bento'), ('luxury_champagne', 'Classic Champagne'), ('luxury_forest', 'Forest Regency'), ('luxury_terracotta', 'Warm Terracotta'), ('brutal_pink', 'Retro Pop Pink'), ('brutal_citrus', 'Cyber Citrus'), ('brutal_violet', 'Electric Violet'), ('cyber_magenta', 'Cyber Magenta'), ('cyber_cyan', 'Cyber Cyan'), ('cyber_sunset', 'Synthwave Sunset'), ('neumorphic_pearl', 'Soft Pearl Neumorphic'), ('neumorphic_obsidian', 'Obsidian Neumorphic'), ('neumorphic_sage', 'Sage Neumorphic')], default='warm_luxury', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='dashboard_theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage'), ('bento_cyber', 'Cyber Obsidian Bento'), ('bento_slate', 'Soft Slate Bento'), ('bento_amber', 'Royal Amber Bento'), ('luxury_champagne', 'Classic Champagne'), ('luxury_forest', 'Forest Regency'), ('luxury_terracotta', 'Warm Terracotta'), ('brutal_pink', 'Retro Pop Pink'), ('brutal_citrus', 'Cyber Citrus'), ('brutal_violet', 'Electric Violet'), ('cyber_magenta', 'Cyber Magenta'), ('cyber_cyan', 'Cyber Cyan'), ('cyber_sunset', 'Synthwave Sunset'), ('neumorphic_pearl', 'Soft Pearl Neumorphic'), ('neumorphic_obsidian', 'Obsidian Neumorphic'), ('neumorphic_sage', 'Sage Neumorphic')], default='emerald_minimal', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='theme',
            field=models.CharField(choices=[('warm_luxury', 'Warm Luxury'), ('midnight_glass', 'Midnight Glass'), ('emerald_minimal', 'Emerald Minimal'), ('sapphire_luxury', 'Royal Sapphire Indigo'), ('midnight_cyber', 'Obsidian Cyber Dark'), ('graffiti_street', 'Graffiti Street Art'), ('graffiti_pink', 'Graffiti Pink Asphalt'), ('graffiti_lime', 'Graffiti Lime Purple'), ('graffiti_cyan', 'Graffiti Cyan Orange'), ('glass_emerald', 'Glassmorphism Emerald'), ('glass_sapphire', 'Glassmorphism Sapphire'), ('glass_crimson', 'Glassmorphism Crimson'), ('clay_blue', 'Claymorphism Pastel Blue'), ('clay_peach', 'Claymorphism Pastel Peach'), ('clay_sage', 'Claymorphism Pastel Sage'), ('bento_cyber', 'Cyber Obsidian Bento'), ('bento_slate', 'Soft Slate Bento'), ('bento_amber', 'Royal Amber Bento'), ('luxury_champagne', 'Classic Champagne'), ('luxury_forest', 'Forest Regency'), ('luxury_terracotta', 'Warm Terracotta'), ('brutal_pink', 'Retro Pop Pink'), ('brutal_citrus', 'Cyber Citrus'), ('brutal_violet', 'Electric Violet'), ('cyber_magenta', 'Cyber Magenta'), ('cyber_cyan', 'Cyber Cyan'), ('cyber_sunset', 'Synthwave Sunset'), ('neumorphic_pearl', 'Soft Pearl Neumorphic'), ('neumorphic_obsidian', 'Obsidian Neumorphic'), ('neumorphic_sage', 'Sage Neumorphic')], default='warm_luxury', max_length=50),
        ),
    ]
