# Generated by Django 4.2.30 on 2026-08-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_add_gateway_sms_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, default='', help_text='Razorpay Key Secret — never exposed in API responses', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Razorpay Webhook Secret — never exposed in API responses', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, default='', help_text='API Key / Account SID / Auth Key for the SMS provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_api_secret',
            field=models.CharField(blank=True, default='', help_text='API Secret / Auth Token — never exposed in API responses', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_from_number',
            field=models.CharField(blank=True, default='', help_text='Twilio: From phone number (e.g. +1XXXXXXXXXX)', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_provider',
            field=models.CharField(choices=[('none', 'None (Demo mode — use 000000)'), ('exotel', 'Exotel'), ('twilio', 'Twilio'), ('msg91', 'MSG91'), ('fast2sms', 'Fast2SMS'), ('textlocal', 'TextLocal')], default='none', help_text='Active SMS gateway for OTP delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, default='', help_text='Sender ID shown to recipient (e.g. RENTLO)', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='sms_template_id',
            field=models.CharField(blank=True, default='', help_text='DLT Template ID (required for Indian carriers via MSG91 / Fast2SMS)', max_length=50),
        ),
    ]
