# Generated by Django 4.2.30 on 2026-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_alter_platformsettings_razorpay_key_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='validity_apt_pg_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_commercial_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_residential_days',
            field=models.IntegerField(default=30),
        ),
    ]
