# Generated by Django 4.2.30 on 2026-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_platformsettings_validity_apt_pg_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='validity_apt_pg_10pack_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_apt_pg_1pack_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_apt_pg_3pack_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_apt_pg_6pack_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='validity_commercial_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='validity_residential_days',
            field=models.IntegerField(default=0),
        ),
    ]
