# Generated by Django 4.2.30 on 2026-08-22 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_platformsettings_validity_apt_pg_10pack_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='company_logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_name',
            field=models.CharField(default='Rentlo Technologies Private Limited', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
