# Generated by Django 4.2.30 on 2026-08-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_propertyauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_1_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_1_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_2_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_2_price',
            field=models.DecimalField(decimal_places=2, default=49.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_3_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_3_price',
            field=models.DecimalField(decimal_places=2, default=89.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_4_days',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='pg_custom_duration_4_price',
            field=models.DecimalField(decimal_places=2, default=149.0, max_digits=10),
        ),
    ]
