# Generated by Django 4.2.30 on 2026-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_platformsettings_pg_custom_duration_1_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyauditlog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='event_category',
            field=models.CharField(choices=[('lifecycle', 'Lifecycle & Status'), ('moderation', 'Moderation & Safety'), ('pricing', 'Pricing & Rent'), ('lead_unlock', 'Leads & Contact Unlocks'), ('media', 'Photos & Media'), ('security', 'Security & Fraud Flags'), ('system', 'System & Automation')], default='lifecycle', max_length=50),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='propertyauditlog',
            index=models.Index(fields=['property', '-changed_at'], name='properties__propert_abf1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyauditlog',
            index=models.Index(fields=['event_category'], name='properties__event_c_6ed678_idx'),
        ),
    ]
