# Generated by Django 4.2.30 on 2026-08-29 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0046_alter_propertyauditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_phone', models.CharField(max_length=20)),
                ('tenant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('package_type', models.CharField(choices=[('basic_kyc', 'Basic KYC (Aadhaar & Contact) - ₹199'), ('employment_check', 'Employment & Salary Verification - ₹399'), ('comprehensive_police', 'Comprehensive Police & Court Check - ₹699')], default='basic_kyc', max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=199.0, max_digits=10)),
                ('id_proof_type', models.CharField(default='aadhaar', max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_slip_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Document Submission'), ('in_review', 'Verification In Progress'), ('verified', 'Verified ✓'), ('flagged', 'Discrepancy / Flagged ⚠'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('verification_score', models.IntegerField(default=95, help_text='Trust Score out of 100')),
                ('report_notes', models.TextField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_verifications_ordered', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_verifications', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PGResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('room_number', models.CharField(help_text='e.g. 101, 204', max_length=50)),
                ('bed_number', models.CharField(help_text='e.g. Bed A, Bed B, Single', max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=True)),
                ('check_in_date', models.DateField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active Resident'), ('notice_period', 'Serving Notice Period (30 Days)'), ('vacated', 'Vacated / Checked Out')], default='active', max_length=30)),
                ('mess_opted', models.BooleanField(default=True, help_text='Opted for monthly mess/meals')),
                ('mess_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_proof_type', models.CharField(default='aadhaar', max_length=50)),
                ('id_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('last_rent_paid_month', models.CharField(blank=True, help_text='e.g. August 2026', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_residents', to='properties.property')),
            ],
            options={
                'ordering': ['room_number', 'bed_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing / Water Leakage'), ('electrical', 'Electrical / Power Issue'), ('appliance', 'Appliance (Geyser, AC, Fan)'), ('carpentry', 'Carpentry / Door / Locks'), ('painting', 'Painting & Wall Seepage'), ('cleaning', 'Pest Control & Deep Cleaning'), ('other', 'Other General Repair')], default='plumbing', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low (Routine)'), ('medium', 'Medium (Standard)'), ('high', 'High (Urgent)'), ('emergency', 'Emergency (Immediate Action)')], default='medium', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open / Reported'), ('assigned', 'Vendor Assigned'), ('in_progress', 'Repair In Progress'), ('resolved', 'Resolved ✓'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('assigned_vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_vendor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='properties.property')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
