# Generated by Django 4.2.30 on 2026-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_tenantverificationrequest_pgresident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payout_account_holder_name',
            field=models.CharField(blank=True, default='', help_text='Company / Admin Account Holder Name', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_account_number',
            field=models.CharField(blank=True, default='', help_text='Bank Account Number from which payouts are sent', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_bank_name',
            field=models.CharField(blank=True, default='HDFC Bank', help_text='Bank Name for outgoing payouts', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payout_ifsc_code',
            field=models.CharField(blank=True, default='', help_text='IFSC Code of the payout bank branch', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='razorpayx_account_number',
            field=models.CharField(blank=True, default='', help_text='RazorpayX Virtual Payout Account Number (e.g. 23232300XXXXXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='razorpayx_key_id',
            field=models.CharField(blank=True, default='', help_text='RazorpayX Payout Key ID (defaults to razorpay_key_id if blank)', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='razorpayx_key_secret',
            field=models.CharField(blank=True, default='', help_text='RazorpayX Payout Key Secret — never exposed in API responses', max_length=255),
        ),
    ]
