# Generated by Django 4.2.30 on 2026-09-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_platformsettings_payout_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='validity_commercial_10pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_commercial_1pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_commercial_3pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_commercial_6pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_residential_10pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_residential_1pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_residential_3pack_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='validity_residential_6pack_days',
            field=models.IntegerField(default=0),
        ),
    ]
