# Generated by Django 4.2.30 on 2026-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_platformsettings_validity_commercial_10pack_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='count_apt_pg_10pack',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_apt_pg_1pack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_apt_pg_3pack',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_apt_pg_6pack',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_buyer_pro',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_buyer_single',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_buyer_smart',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_buyer_starter',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_commercial_10pack',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_commercial_1pack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_commercial_3pack',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_commercial_6pack',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_residential_10pack',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_residential_1pack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_residential_3pack',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='count_residential_6pack',
            field=models.IntegerField(default=6),
        ),
    ]
