# Generated by Django 4.2.30 on 2026-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_platformsettings_count_apt_pg_10pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'property_category', 'locality'], name='properties__status_2c9bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties__owner_i_30ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'expires_at'], name='properties__status_4efab3_idx'),
        ),
    ]
