# Generated by Django 4.2.30 on 2026-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='enable_watermark',
            field=models.BooleanField(default=True, help_text='Automatically overlay watermark on uploaded property photos'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='watermark_text',
            field=models.CharField(blank=True, default='Verified on Rentlo.in', help_text='Custom watermark text stamped on property photos', max_length=100),
        ),
    ]
