# Generated by Django 6.0.8 on 2026-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_propertymedia_medium_url_propertymedia_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
